### ISSUE TITLE
Missing Devices.

### ISSUE THREAD

**Issue by rwijbenga** [alexander-vitishchenko/hc3-to-mqtt#5] opened 2021-07-05 20:26 UTC
Love your plug-in!! :)

I now have a HC2 running with 100+ devices, and I have already a HC3. But I first need to get the link between HC3 and HASS correctly working. As the normal HC3 interface in HASS is not 100% working I turned to your plug-in. But I have some devices missing.

First a temperature and moisture sensor, I only see the temperature now and missing the moisture reading in HASS. This is the JSON from the device: 

Parrent:

{"id":37,"name":"36.0","roomID":219,"view":[{"assetsPath":"/dynamic-plugins/com.fibaro.multilevelSensor/assets","jsPath":"/dynamic-plugins/com.fibaro.multilevelSensor","name":"com.fibaro.multilevelSensor","translatesPath":"/assets/i18n","type":"ts"}],"type":"com.fibaro.multilevelSensor","baseType":"com.fibaro.sensor","enabled":true,"visible":true,"isPlugin":false,"parentId":36,"viewXml":false,"configXml":false,"interfaces":["battery","fibaroFirmwareUpdate","tamper","zwave","zwaveAlarm","zwaveWakeup"],"properties":{"parameters":[],"pollingTimeSec":0,"wakeUpTime":86400,"zwaveCompany":"Philio Technology Corp","zwaveInfo":"3,4,5","zwaveVersion":"1.14","alarmLevel":0,"alarmType":0,"batteryLevel":100,"batteryLowNotification":true,"categories":["other"],"configured":true,"dead":false,"deadReason":"","defInterval":0,"deviceControlType":0,"deviceIcon":47,"endPointId":0,"firmwareUpdate":{"info":"","progress":0,"status":"UpToDate","updateVersion":"1.14"},"log":"","logTemp":"","manufacturer":"","markAsDead":true,"maxInterval":0,"minInterval":0,"model":"","nodeId":6,"parametersTemplate":"0","pendingActions":false,"productInfo":"1,60,0,2,0,32,1,14","saveLogs":true,"serialNumber":"h'100d46e5","stepInterval":0,"tamper":false,"unit":"","updateVersion":"","useTemplate":true,"userDescription":"","value":0.0},"actions":{"abortUpdate":1,"reconfigure":0,"retryUpdate":1,"setInterval":1,"startUpdate":1,"updateFirmware":1},"created":1625515690,"modified":1625515690,"sortOrder":11}

Child1: 

{"id":38,"name":"36.0.1","roomID":219,"view":[{"assetsPath":"/dynamic-plugins/com.fibaro.securitySensor/assets","jsPath":"/dynamic-plugins/com.fibaro.securitySensor","name":"com.fibaro.securitySensor","translatesPath":"/dynamic-plugins/com.fibaro.securitySensor/i18n","type":"ts"}],"type":"com.fibaro.motionSensor","baseType":"com.fibaro.securitySensor","enabled":true,"visible":true,"isPlugin":false,"parentId":36,"viewXml":false,"configXml":false,"interfaces":["battery","fibaroBreach","zwave","zwaveWakeup"],"properties":{"parameters":[],"pollingTimeSec":0,"wakeUpTime":86400,"zwaveCompany":"Philio Technology Corp","zwaveInfo":"3,4,5","zwaveVersion":"1.14","batteryLevel":100,"batteryLowNotification":true,"categories":["security"],"configured":true,"dead":false,"deadReason":"","defInterval":0,"deviceControlType":0,"deviceIcon":21,"endPointId":0,"lastBreached":0,"log":"","logTemp":"","manufacturer":"","markAsDead":true,"maxInterval":0,"minInterval":0,"model":"","nodeId":6,"parametersTemplate":"0","pendingActions":false,"productInfo":"1,60,0,2,0,32,1,14","saveLogs":true,"serialNumber":"h'100d46e5","stepInterval":0,"useTemplate":true,"userDescription":"","value":false},"actions":{"reconfigure":0,"setInterval":1},"created":1625515690,"modified":1625515690,"sortOrder":12}

Child2: 

{"id":39,"name":"36.0.2","roomID":219,"view":[{"assetsPath":"/dynamic-plugins/com.fibaro.multilevelSensor/assets","jsPath":"/dynamic-plugins/com.fibaro.multilevelSensor","name":"com.fibaro.multilevelSensor","translatesPath":"/assets/i18n","type":"ts"}],"type":"com.fibaro.temperatureSensor","baseType":"com.fibaro.multilevelSensor","enabled":true,"visible":true,"isPlugin":false,"parentId":36,"viewXml":false,"configXml":false,"interfaces":["battery","zwave","zwaveWakeup"],"properties":{"parameters":[],"pollingTimeSec":0,"wakeUpTime":86400,"zwaveCompany":"Philio Technology Corp","zwaveInfo":"3,4,5","zwaveVersion":"1.14","batteryLevel":100,"batteryLowNotification":true,"categories":["climate"],"configured":true,"dead":false,"deadReason":"","defInterval":0,"deviceControlType":0,"deviceIcon":30,"endPointId":0,"log":"","logTemp":"","manufacturer":"","markAsDead":true,"maxInterval":0,"minInterval":0,"model":"","nodeId":6,"offset":0.0,"parametersTemplate":"0","pendingActions":false,"productInfo":"1,60,0,2,0,32,1,14","saveLogs":true,"serialNumber":"h'100d46e5","showFireAlarm":true,"showFreezeAlarm":false,"stepInterval":0,"unit":"C","useTemplate":true,"userDescription":"","value":20.9},"actions":{"reconfigure":0,"setInterval":1},"created":1625515690,"modified":1625515690,"sortOrder":13}

Child3:

{"id":40,"name":"36.0.3","roomID":219,"view":[{"assetsPath":"/dynamic-plugins/com.fibaro.multilevelSensor/assets","jsPath":"/dynamic-plugins/com.fibaro.multilevelSensor","name":"com.fibaro.multilevelSensor","translatesPath":"/assets/i18n","type":"ts"}],"type":"com.fibaro.humiditySensor","baseType":"com.fibaro.multilevelSensor","enabled":true,"visible":true,"isPlugin":false,"parentId":36,"viewXml":false,"configXml":false,"interfaces":["battery","zwave","zwaveWakeup"],"properties":{"parameters":[],"pollingTimeSec":0,"wakeUpTime":86400,"zwaveCompany":"Philio Technology Corp","zwaveInfo":"3,4,5","zwaveVersion":"1.14","batteryLevel":100,"batteryLowNotification":true,"categories":["other"],"configured":true,"dead":false,"deadReason":"","defInterval":0,"deviceControlType":0,"deviceIcon":31,"endPointId":0,"log":"","logTemp":"","manufacturer":"","markAsDead":true,"maxInterval":0,"minInterval":0,"model":"","nodeId":6,"parametersTemplate":"0","pendingActions":false,"productInfo":"1,60,0,2,0,32,1,14","saveLogs":true,"serialNumber":"h'100d46e5","stepInterval":0,"unit":"%","useTemplate":true,"userDescription":"","value":82.03},"actions":{"reconfigure":0,"setInterval":1},"created":1625515690,"modified":1625515690,"sortOrder":14}

And A Fibaro wall plug switch, this is the JSON from that device:

{"id":35,"name":"StekkerHC3","roomID":221,"view":[{"assetsPath":"/dynamic-plugins/com.fibaro.binarySwitch/assets","jsPath":"/dynamic-plugins/com.fibaro.binarySwitch","name":"com.fibaro.binarySwitch","translatesPath":"/dynamic-plugins/com.fibaro.binarySwitch/i18n","type":"ts"},{"assetsPath":"/dynamic-plugins/energy/assets","jsPath":"/dynamic-plugins/energy","name":"energy","translatesPath":"/dynamic-plugins/energy/i18n","type":"ts"},{"assetsPath":"/dynamic-plugins/power/assets","jsPath":"/dynamic-plugins/power","name":"power","translatesPath":"/dynamic-plugins/power/i18n","type":"ts"}],"type":"com.fibaro.FGWP102","baseType":"com.fibaro.FGWP","enabled":true,"visible":true,"isPlugin":false,"parentId":34,"viewXml":false,"configXml":false,"interfaces":["energy","fibaroFirmwareUpdate","light","power","zwave","zwaveAlarm","zwaveMultiChannelAssociation"],"properties":{"parameters":[{"id":1,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":2,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":3,"lastReportedValue":0,"lastSetValue":0,"size":2,"value":0},{"id":10,"lastReportedValue":80,"lastSetValue":80,"size":1,"value":80},{"id":11,"lastReportedValue":15,"lastSetValue":15,"size":1,"value":15},{"id":12,"lastReportedValue":30,"lastSetValue":30,"size":2,"value":30},{"id":13,"lastReportedValue":10,"lastSetValue":10,"size":2,"value":10},{"id":14,"lastReportedValue":3600,"lastSetValue":3600,"size":2,"value":3600},{"id":15,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":20,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":21,"lastReportedValue":300,"lastSetValue":300,"size":2,"value":300},{"id":22,"lastReportedValue":500,"lastSetValue":500,"size":2,"value":500},{"id":23,"lastReportedValue":6,"lastSetValue":6,"size":1,"value":6},{"id":24,"lastReportedValue":255,"lastSetValue":255,"size":2,"value":255},{"id":30,"lastReportedValue":63,"lastSetValue":63,"size":1,"value":63},{"id":31,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":32,"lastReportedValue":600,"lastSetValue":600,"size":2,"value":600},{"id":40,"lastReportedValue":25000,"lastSetValue":25000,"size":2,"value":25000},{"id":41,"lastReportedValue":1,"lastSetValue":1,"size":1,"value":1},{"id":42,"lastReportedValue":0,"lastSetValue":0,"size":1,"value":0},{"id":43,"lastReportedValue":2,"lastSetValue":2,"size":1,"value":2},{"id":50,"lastReportedValue":3,"lastSetValue":3,"size":1,"value":3}],"pollingTimeSec":0,"zwaveCompany":"Fibargroup","zwaveInfo":"3,4,24","zwaveVersion":"3.2","alarmLevel":0,"alarmType":0,"categories":["lights"],"color":"white","configured":true,"dead":false,"deadReason":"","deviceControlType":2,"deviceIcon":125,"endPointId":0,"energy":0.0,"firmwareUpdate":{"info":"","progress":0,"status":"UpToDate","updateVersion":"3.2"},"icon":{"path":"assets/icon/fibaro/onoff/onoff100.png","source":"HC"},"isLight":true,"log":"","logTemp":"","manufacturer":"","markAsDead":true,"model":"","nodeId":5,"parametersTemplate":"741","power":0.0,"productInfo":"1,15,6,2,16,3,3,2","saveLogs":true,"serialNumber":"h'0000000000022a2a","showEnergy":true,"state":true,"updateVersion":"","useTemplate":true,"userDescription":"","value":true},"actions":{"abortUpdate":1,"reconfigure":0,"reset":0,"retryUpdate":1,"startUpdate":1,"toggle":0,"turnOff":0,"turnOn":0,"updateFirmware":1},"created":1625515690,"modified":1625515690,"sortOrder":9}

I hope you can add those devices. :) 
Or is there a way to add them myself? I think I will have more devices missing when I am going to transfer everything to the HC3. But if you add then, it will make your plug-in more complete for all the users.....

Keep up the good work!

**Comment by alexander-vitishchenko** [comment] 2021-07-07 17:05
Hi @rwijbenga !

Let me look at it during weekend, definitely worth adding new device types.

Wish I had physical devices to do the implementation and testing in one go. And thank you providing device info in JSON format.

**Comment by rwijbenga** [comment] 2021-07-07 20:00
Let me know what you need for testing.. Love to help!

**Comment by rwijbenga** [comment] 2021-07-15 09:47
Hi @alexander-vitishchenko 

Did you have a chance to take a look? :)

**Comment by alexander-vitishchenko** [comment] 2021-07-19 19:40
Yes - just need more time :), as I don't have a physical device

I expect the implementation to be done this weekend, and then you do the testing

**Comment by rwijbenga** [comment] 2021-07-26 08:39
Will keep my eye on this thread then... :)

**Comment by alexander-vitishchenko** [comment] 2021-07-28 18:27
@rwijbenga just to keep you updated - I've added support for humidity sensor, but not yet committed to repository as I'm keep working on your Fibaro wall plug switch, aka "StekkerHC3" :)

**Comment by alexander-vitishchenko** [comment] 2021-07-28 18:40
I've just added support for Fibaro wall plug, and I'll commit the changes later today so you can check it out

**Comment by rwijbenga** [comment] 2021-07-31 13:29
@alexander-vitishchenko 

I updated the plugin in Fibaro, with the same variables as before, and it is not working anymore. I get this error:

MQTT ERROR: {"code":2}

I have tried setting the variable mqttClientId but that did not solve the problem....

Going back to the older version and everything works again.

So i think there is something broken now in the code..... 

What can I do to help / fix it?

**Comment by alexander-vitishchenko** [comment] 2021-08-02 21:34
@rwijbenga 

There are two news:
- MQTT error is something what doesn't look related to my changes and I cannot reproduce it with my setup, need more time to investigate
- On the positive side, I've purchased "Fibaro wall plug" to play with and to test device integration for you :)

**Comment by rwijbenga** [comment] 2021-08-05 07:43
Let me know if I can help again... :)

And I hope you don't need all the devices I have, I think there are some more devices that need support.. ;)

**Comment by alexander-vitishchenko** [comment] 2021-08-08 11:53
@rwijbenga I've submitted the fix - please check it out

Happy to add support for more device types, especially if you send them over to me... as it significantly improves my velocity, and I don't mind to have more staff in my home lab :)

**Comment by rwijbenga** [comment] 2021-08-09 09:52
It works again... :)

Now to test some more devices.

One error I notice is in Home Assistant is this:

The 'value_template' option is deprecated, please replace it with 'state_value_template' 

I use the latest Home Assistant

I don't have any spare devices to send you, but I could make a donation to paypal to support your work. 👍

**Comment by alexander-vitishchenko** [comment] 2021-08-10 11:06
1) Great! Just to double-check => both Fibaro wall plug and humidity sensor work for you, right?

2) I'll update "value_template" with "state_value_template" with the next commit. Thanks!

3) I can add support for as many devices as you ask, and PayPal works for me :) Not only because of the "sake of humanity" ;) but also because I enjoy trying new devices at my home

**Comment by alexander-vitishchenko** [comment] 2021-08-12 01:50
@rwijbenga 

New feature requests make sense, I plan to do the following this weekend:
- rounding numeric values to 2 decimals
- "value_template" => "state_value_template"
- add "Donate" button to GitHub project
- explore Power Meter API for HC3 <-> HA. Implement the integration if it appears straightforward... or I'll provide ETA if it takes more than a single weekend

Note: I suggest tracking new feature requests as separate issues/tickets, so we can prioritize them separately and track granular status on implementation

Note 2: There is a chance I may not have remote access to my Smart Home (development environment), because I travel to Berlin for August 12-22, but hopefully everything will work fine

**Comment by alexander-vitishchenko** [comment] 2021-08-15 23:18
@rwijbenga 

Done:
- Implemented rounding for numeric values (up to 2 decimals). Trivia: Lua has no "round" function out-of-the-box, so I had to "reinvent" it myself
- Actualized MQTT "value_template" property for light device type => now it is "state_value_template". Can you please check if your Home Assistant logs are good now? 
- Energy/Power Meter API - I've created a new issue to track its status separately. Need more R&D work to happen over the next few weekends
- Added "Donate" button to the main page of this GitHub project, feel free to use ;-)

**Closed by alexander-vitishchenko** 2021-08-15 23:18 UTC

**Comment by rwijbenga** [comment] 2021-08-19 19:50
No template error anymore... :)

Everything works.

Donation done.

And I have some new devices to add. But will create case for those later, you have enough on your plate now...
