### ISSUE TITLE
Change MQTT Topic

### ISSUE THREAD

**Issue by MomosX** [alexander-vitishchenko/hc3-to-mqtt#33] opened 2022-11-24 09:49 UTC
I have tried to change the MQTT topic to something like HC3/ . Made the change in mqtt_convention_api.lua line 39.

MqttConventionHomeAssistant = inheritFrom(MqttConventionPrototype) 
MqttConventionHomeAssistant.type = "Home Assistant"
MqttConventionHomeAssistant.rootTopic = "HC3/"

Bridge starts but HA does't see any device.  

For sure i'm missing something :)  Please help.

PS: need to change the topic as i have quite a few Mqtt devices , all flooding homeasisstant topic.

Thank you !

**Comment by alexander-vitishchenko** [comment] 2022-11-25 20:46
Home Assistant MQTT Discovery specification requires "homeassistant" root folder to be used by default. See https://www.home-assistant.io/integrations/mqtt for details.

If you want Home Assistant to listen for events in a different root folder - try reading HA manual https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery, but I've never tried doing so.


Can you please advise what is exactly the problem you are trying to resolve? There must be a different and maybe even a better way to get it done.

**Comment by MomosX** [comment] 2022-11-25 21:30
Let me try to explain what is happening since first version of the QA.

Sometimes i make modifications to device parameters, delete or add a device in HC3.  For some reason from time to time i see all the entities from HC3 in HA as unavailable.  I stop the QA and restart it... but .. HA indexes the entities with _2, _3 and so on.  
The way i'm solving this now is by opening MQTT Explorer, let it run a bit, then delete all homeassitant topics/messages and restart the QA.
Then all is good.  But unfortunatelly in the topic homeassistant there are some other entities provided by other integrations.  So i have to go restart those integrations again. 
Deleting only the HC3 entities from MQTT Explorer is a pain as there are many of them.

Maybe there is a way to tell the QA when is starts to clear all messages/topics ?

**Comment by Usever** [comment] 2022-11-26 11:47
> Sometimes i make modifications to device parameters, delete or add a device in HC3. For some reason from time to time i see all the entities from HC3 in HA as unavailable. I stop the QA and restart it... but .. HA indexes the entities with _2, _3 and so on.

To me it also happens on a simple HC3 reboot, not for the all entities, but some are also getting new indexes _2, _3, second reboot resolves it.

**Comment by alexander-vitishchenko** [comment] 2022-11-26 14:30
Can you please share few examples, how you edit Fibaro devices? 

+ share the corresponding log file from the Fibaro QuickApp? And ideally Home Assistant log file from MQTT integration component?

I'm pretty sure this is something what I can fix if the problem is on QuickApp side (not how HA MQTT specs designed to work). Just need more details.

And then you no longer need to purge devices via MQTT Explorer that impact other integrations :-)

**Comment by alexander-vitishchenko** [comment] 2022-12-15 09:34
Hi @Usever,

Just to keep you updated - there is ongoing discussion about solution design at #35

**Comment by alexander-vitishchenko** [comment] 2022-12-19 08:51
Hi @MomosX can you please advise if this issue is a duplicate of #35, and we can close it?

**Comment by MomosX** [comment] 2022-12-19 09:13
yup . same issue. can be closed.  The only way things will get messed up now is if we exclude/include a device in HC3 or do something that changes the device ID in HC3.  Which of course is not something this QA can solve:)

**Comment by alexander-vitishchenko** [comment] 2022-12-19 14:21
QuickApp is actually able to get events from Fibaro HC3 about devices added/changed/removed, and keep Home Assistant in sync without restart.

If this request is different than #35, then let's not close it as duplicate, and spend a bit more time to investigate what you initially proposed? Ideally in a form of a few scenarios so I see what you propose and why this would be valuable.

Sorry for not being able to get the idea initially, and Il just trying to help :-)

**Comment by MomosX** [comment] 2022-12-19 15:07
Originally i wanted to change the MQTT topic all together, just to be able able to purge HC3 entities when something went wrong and i had misslabled entities.  That was the only reason.
Now the need to purge the MQTT is gone as it was solved here #35 . The fix is a long term one and for the last 24h i've been trying to "break" it with no success. 
I even excluded devices from HC3 and reincluded to see what happens.  All went good.  
From my point of view the reason i opened this request is gone.

**Closed** 2022-12-19 15:31 UTC
