### ISSUE TITLE
Temperatures do not update from Fibaro Multisensors

### ISSUE THREAD

**Issue by JoonasFI** [alexander-vitishchenko/hc3-to-mqtt#23] opened 2022-06-17 10:12 UTC
Hi!

Weird problem. Temperatures do not update from Fibaro Multisensors, except when I reboot HA. Any ideas?

Thank you!

PS: I tried to donate 20 € via Paypal and credit card. I got message "...this payment can't be completed due to regulations."

Hope you are OK!

**Comment by alexander-vitishchenko** [comment] 2022-06-17 14:49
Hi @JoonasFI 

I can try to investigate the issue this weekend, just need you to provide me with (a) logs and (b) JSON for your Fibaro Multisensors. Hopefully, this is something easy to resolve.

I'm OK as much as it is possible during the crisis. And it would be great if you know anyone who has an apartment for $$ rent in Berlin, or not far away from it. I've just changed PayPal details to address my mother's account which worked in the past.

**Comment by JoonasFI** [comment] 2022-06-18 11:49
Here you go. Hopefully the files are correct.

I have a few friends in Berlin. I passed them a message about the apartment
[ha-log.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/89334
[fibaro-multisensor-eteinen-xml.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/8933464/fibaro-multisensor-eteinen-xml.txt)
61/ha-log.txt)
[mqtt-json.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/8933463/mqtt-json.txt)
.

**Comment by JoonasFI** [comment] 2022-06-18 12:09
Few images from Fibaro, if these are essential.

![fibaro-1](https://user-images.githubusercontent.com/25513442/174436803-92b26c5a-6d29-48cc-809b-d93c7b8cb27f.png)

![fibaro-2](https://user-images.githubusercontent.com/25513442/174436805-d930bb20-96bc-4360-88dd-888766790449.png)

**Comment by alexander-vitishchenko** [comment] 2022-06-20 16:07
Can you please also share logs from Fibaro HC3 console?

Activated from the main screen:
<img width="57" alt="image" src="https://user-images.githubusercontent.com/1070777/174641842-be102862-3a70-4a13-bc18-a11c4dd0bf3c.png">

Log records looks like and should be ideally saved to *.txt file:
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/1070777/174642038-d133c815-27b3-4307-acd8-441cabe0c35e.png">

**Comment by JoonasFI** [comment] 2022-06-20 17:59
Here you go. :)

[fibaro-console.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/8942829/fibaro-console.txt)

**Comment by JoonasFI** [comment] 2022-06-20 18:01
Here you go. :)

[fibaro-console.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/8942837/fibaro-console.txt)

**Comment by alexander-vitishchenko** [comment] 2022-10-15 18:34
Hi @JoonasFI 

Please let me know if the request is still relevant for you?

And if so I'll try to check the log files and then see what should be our next steps.

Thank you,
Alexander

P.S.: apologies for late reply as I only finished my accommodation in Berlin after moving from Kyiv

**Comment by JoonasFI** [comment] 2022-10-17 10:53
Hi!

Request is still relevant.

It seems that status changes do not update to HA. For ex. temperatures or state of lights. So if I turn light on from Fibaro app, HA shows it still in off mode.

:)

**Comment by alexander-vitishchenko** [comment] 2022-10-17 12:18
Hi @JoonasFI,

I can see MQTT error code 111 in the logs, i.e. MQTT connection refused.

1) Do you use Mosquitto MQTT broker?
2) Are you able to connect to Mosquitto with let's say MQTT Explorer http://mqtt-explorer.com/?
3) Can you please share sensor ids where you see trouble?
4) Plus need you to send me description for one of your sensors in JSON format, which is available from your Swagger UI => "devices" => GET /devices/{deviceID}?

**Comment by JoonasFI** [comment] 2022-10-17 14:11
1. Yes.
2. Seems to work OK. 
3. For example 90 (multi sensor) or 129 (relay)
4. One of the multi sensors:

{
    "id": 90,
    "name": "Lattian lämpötila",
    "roomID": 224,
    "view": [
      {
        "assetsPath": "dynamic-plugins/com.fibaro.multilevelSensor",
        "name": "com.fibaro.multilevelSensor",
        "translatesPath": "/assets/i18n",
        "type": "ts"
      }
    ],
    "type": "com.fibaro.temperatureSensor",
    "baseType": "com.fibaro.multilevelSensor",
    "enabled": true,
    "visible": true,
    "isPlugin": false,
    "parentId": 85,
    "viewXml": false,
    "hasUIView": false,
    "configXml": false,
    "interfaces": [
      "zwave"
    ],
    "properties": {
      "pollingTimeSec": 0,
      "zwaveCompany": "Fibargroup",
      "zwaveInfo": "3,3,52",
      "zwaveVersion": "2.1",
      "categories": [
        "climate"
      ],
      "configured": true,
      "dead": false,
      "deadReason": "",
      "deviceControlType": 1,
      "deviceIcon": 30,
      "deviceRole": "TemperatureSensor",
      "emailNotificationID": 0,
      "emailNotificationType": 0,
      "endPointId": 3,
      "icon": {},
      "log": "",
      "logTemp": "",
      "manufacturer": "",
      "markAsDead": true,
      "model": "",
      "nodeId": 19,
      "offset": 0,
      "parametersTemplate": 85,
      "productInfo": "1,15,5,1,16,2,2,1",
      "pushNotificationID": 0,
      "pushNotificationType": 0,
      "saveLogs": true,
      "serialNumber": "",
      "showFireAlarm": true,
      "showFreezeAlarm": false,
      "smsNotificationID": 0,
      "smsNotificationType": 0,
      "supportedDeviceRoles": [
        "Other",
        "TemperatureSensor"
      ],
      "unit": "C",
      "useTemplate": true,
      "userDescription": "",
      "value": 23.43
    },
    "actions": {
      "reconfigure": 0
    },
    "created": 1655114101,
    "modified": 1665154016,
    "sortOrder": 65
  },
  
  Another example is lights relay in same room:
  
  {
    "id": 129,
    "name": "Peili",
    "roomID": 224,
    "view": [
      {
        "assetsPath": "dynamic-plugins/com.fibaro.binarySwitch",
        "name": "com.fibaro.binarySwitch",
        "translatesPath": "/assets/i18n/com.fibaro.binarySwitch",
        "type": "ts"
      },
      {
        "assetsPath": "dynamic-plugins/energy",
        "name": "energy",
        "translatesPath": "/assets/i18n/energy",
        "type": "ts"
      },
      {
        "assetsPath": "dynamic-plugins/power",
        "name": "power",
        "translatesPath": "/assets/i18n/power",
        "type": "ts"
      }
    ],
    "type": "com.fibaro.binarySwitch",
    "baseType": "com.fibaro.actor",
    "enabled": true,
    "visible": true,
    "isPlugin": false,
    "parentId": 125,
    "viewXml": false,
    "hasUIView": true,
    "configXml": false,
    "interfaces": [
      "energy",
      "light",
      "power",
      "zwave",
      "zwaveMultiChannelAssociation",
      "zwaveProtection"
    ],
    "properties": {
      "pollingTimeSec": 0,
      "zwaveCompany": "Fibargroup",
      "zwaveInfo": "3,4,24",
      "zwaveVersion": "3.4",
      "RFProtectionState": 0,
      "RFProtectionSupport": 3,
      "categories": [
        "lights"
      ],
      "configured": true,
      "dead": false,
      "deadReason": "",
      "deviceControlType": 2,
      "deviceIcon": 1,
      "deviceRole": "Light",
      "emailNotificationID": 0,
      "emailNotificationType": 0,
      "endPointId": 1,
      "energy": 5.69,
      "icon": {
        "path": "/assets/icon/fibaro/light/light0.png",
        "source": "HC"
      },
      "isLight": true,
      "localProtectionState": 0,
      "localProtectionSupport": 5,
      "log": "",
      "logTemp": "",
      "manufacturer": "",
      "markAsDead": true,
      "model": "",
      "nodeId": 29,
      "parametersTemplate": 781,
      "power": 0,
      "productInfo": "1,15,2,3,16,0,3,4",
      "protectionExclusiveControl": 0,
      "protectionExclusiveControlSupport": false,
      "protectionState": 0,
      "protectionTimeout": 0,
      "protectionTimeoutSupport": false,
      "pushNotificationID": 0,
      "pushNotificationType": 0,
      "saveLogs": true,
      "saveToEnergyPanel": true,
      "serialNumber": "h'0000000000043a4a",
      "showEnergy": true,
      "smsNotificationID": 0,
      "smsNotificationType": 0,
      "state": false,
      "storeEnergyData": true,
      "supportedDeviceRoles": [
        "Light",
        "Drencher",
        "Pin",
        "NightLamp",
        "Kettle",
        "Bracket",
        "AirConditioner",
        "AlarmAlarm",
        "Coffee",
        "GardenLamp",
        "TvSet",
        "CeilingFan",
        "Toaster",
        "Radio",
        "RoofWindow",
        "Other",
        "AlarmState",
        "AlarmArm",
        "VideoGateBell",
        "VideoGateOpen",
        "Valve"
      ],
      "useTemplate": true,
      "userDescription": "",
      "value": false
    },
    "actions": {
      "reconfigure": 0,
      "reset": 0,
      "toggle": 0,
      "turnOff": 0,
      "turnOn": 0
    },
    "created": 1655114101,
    "modified": 1665154017,
    "sortOrder": 100
  },

**Comment by JoonasFI** [comment] 2022-10-17 14:23
https://user-images.githubusercontent.com/25513442/196202422-a1c30c8b-dfcc-427c-8117-93b48a8f6584.mov

**Comment by JoonasFI** [comment] 2022-10-17 20:50
Hmmph! Mosquito Broker log:

```
2022-10-17 23:15:35: New client connected from 192.168.1.40:39082 as HC3-243-1666037735 (p2, c0, k60, u'mosquitto').
2022-10-17 23:16:50: New connection from 172.30.32.2:39182 on port 1883.
2022-10-17 23:16:50: Client <unknown> closed its connection.
2022-10-17 23:18:50: New connection from 172.30.32.2:35498 on port 1883.
2022-10-17 23:18:50: Client <unknown> closed its connection.
2022-10-17 23:20:50: New connection from 172.30.32.2:33556 on port 1883.
2022-10-17 23:20:50: Client <unknown> closed its connection.
2022-10-17 23:22:25: New connection from 192.168.1.58:61155 on port 1883.
```
MQTT(?) drops every 2 mins. Can this be the problem...

**Comment by JoonasFI** [comment] 2022-10-17 20:51
Hmmph! Mosquito Broker log:

```
2022-10-17 23:15:35: New client connected from 192.168.1.40:39082 as HC3-XXX-XXXXXXXX (p2, c0, k60, u'mosquitto').
2022-10-17 23:16:50: New connection from 172.30.32.2:39182 on port 1883.
2022-10-17 23:16:50: Client <unknown> closed its connection.
2022-10-17 23:18:50: New connection from 172.30.32.2:35498 on port 1883.
2022-10-17 23:18:50: Client <unknown> closed its connection.
2022-10-17 23:20:50: New connection from 172.30.32.2:33556 on port 1883.
2022-10-17 23:20:50: Client <unknown> closed its connection.
2022-10-17 23:22:25: New connection from 192.168.1.58:61155 on port 1883.
```
MQTT(?) drops every 2 mins. Can this be the problem...

**Comment by alexander-vitishchenko** [comment] 2022-10-20 20:12
Hi @JoonasFI 

Yes - I believe MQTT connectivity is the reason, which prevents events to be transferred from HC3 to Home Assistant 

Let me think why it happens, and thanks for providing logs and video recordings, this helps to narrow down the issue

**Comment by JoonasFI** [comment] 2022-10-21 21:42
Hi!

1. All status updates are interrupt.
2. Sure!
3. I have local network buildt with UDM Pro. I check and firewall rules. My HA installation runs on Mac Mini (Virtual Box).

**Comment by alexander-vitishchenko** [comment] 2022-10-22 08:58
1. If so, then this certainly looks like an MQTT connectivity issue
2. Thanks, and waiting for the new log file. More info is better
3. Btw, I'm using UDM Pro too :-)

**Comment by alexander-vitishchenko** [comment] 2022-11-06 20:52
Hi @JoonasFI 

Please let me know if you still experience the issue, or this ticket could be closed? 

I'm curious to learn the root cause as it might help me guide other users with similar issues in a future.

**Comment by JoonasFI** [comment] 2022-11-08 13:11
Hi! Issue is still valid.

Problem is that there is no new events in log when I do something.

I noticed few things. When I restart quick app in Fibaro, debug shows:

```
[08.11.2022] [15:04:45] [WARNING] [QUICKAPP243]: Variable mqttClientId not found
[08.11.2022] [15:04:45] [WARNING] [QUICKAPP243]: All is good - we have just autogenerated mqttClientId for you "HC3-243-1667912685"
[08.11.2022] [15:04:45] [TRACE] [QUICKAPP243]: MQTT Connection Parameters: {"clientId":"HC3-243-SENSORED","keepAlivePeriod":60,"password":"sensored","username":"sensored","lastWill":{"payload":"true","topic":"homeassistant\/hc3-dead"}}
[08.11.2022] [15:04:46] [DEBUG] [QUICKAPP243]: MQTT connection established

```

And few minutes later...

```
[08.11.2022] [15:08:47] [ERROR] [QUICKAPP243]: QuickApp crashed
[08.11.2022] [15:08:47] [ERROR] [QUICKAPP243]: Unknown error occurred:
```

**Comment by alexander-vitishchenko** [comment] 2022-12-13 18:07
Hi @JoonasFI,

This seems to be most likely network/connectivity related issue. Please let me know if you need my help to dig deeper into details, or the issue could be closed.

**Comment by alexander-vitishchenko** [comment] 2022-12-19 08:53
Hi @JoonasFI,

Happy to assist with the issue resolution if it's about QuickApp, or help you investigate your home network connectivity issues. Please let me know.

As for know - closing the issue to due the expiration while requesting more details.

**Closed by alexander-vitishchenko** 2022-12-19 08:53 UTC
