### ISSUE TITLE
cover:close

### ISSUE THREAD

**Issue by MomosX** [alexander-vitishchenko/hc3-to-mqtt#40] opened 2023-01-01 15:22 UTC
Using the cover: close function from HA  outputs a warning message:

"WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): close"

I think it is related to the state payload from MQTT . Looking at the mqtt_convention_api i think the following should be changed:

            msg.payload_open = "open"
            msg.payload_close = "close"
            msg.payload_stop = "stop"

            msg.state_open = "open"
            msg.state_closed = "close" -- it is "closed" in the QA now
            msg.state_opening = "opening"
            msg.state_closing = "closing"
            msg.state_stopped = "stop" -- missing in the QA now

Happy New Year !!!!!

**Comment by alexander-vitishchenko** [comment] 2023-01-01 15:42
Sure, I can look at it once I'm done with a massive refactoring of the QuickApp this week

**Comment by MomosX** [comment] 2023-01-01 21:01
"massive refactoring of the QuickApp" sounds interesting.

**Comment by alexander-vitishchenko** [comment] 2023-01-02 09:07
Speaking about refactoring, and just to make sure you saw the message from another thread => the QuickApp is now simplified and uses less variables for configuration => no need to pass HC3 user/pass, as the QuickApp passes authorization automatically now

**Comment by MomosX** [comment] 2023-01-02 09:27
yuo saw it :) thank you !

**Comment by alexander-vitishchenko** [comment] 2023-01-08 16:15
@MomosX 

It should be fine use use "closed" (or even "my_favourite_string") for the state_closed parameter, according to Home Assistant MQTT spec.

I believe the fix would be to avoid use of position_topic and state_topic at the same time. I plan to release the QuickApp using position_topic only today. It works for me and then you can test if it works for you too.

**Comment by alexander-vitishchenko** [comment] 2023-01-15 07:53
Hi @MomosX, please let test if the issue is fixed, or persist?

**Comment by alexander-vitishchenko** [comment] 2023-03-27 12:53
The latest QuickApp version addresses multiple changes for Fibaro cover devices.

Closing this issue as outdated / no more inputs received.

**Closed by alexander-vitishchenko** 2023-03-27 12:53 UTC
