### ISSUE TITLE
Z-wave remote support

### ISSUE THREAD

**Issue by rwijbenga** [alexander-vitishchenko/hc3-to-mqtt#11] opened 2021-09-29 09:18 UTC
Plug-in is still working well here. :)

I only have one device not supported , a remote. They sell it only with different brand names. 

https://heatit.com/product/9311/smart-products/controllers/heatit-z-push-button-8-white/1107

This is the JSON for the 8 button version:

`{"id":984,"name":"8 Knoppen Deur","roomID":224,"view":[],"type":"com.fibaro.remoteController","baseType":"com.fibaro.actor","enabled":true,"visible":true,"isPlugin":false,"parentId":983,"viewXml":false,"configXml":false,"interfaces":["battery","fibaroFirmwareUpdate","zwave","zwaveCentralScene","zwaveMultiChannelAssociation","zwaveWakeup"],"properties":{"parameters":[],"pollingTimeSec":0,"wakeUpTime":28800,"zwaveCompany":"Heatit","zwaveInfo":"3,5,3","zwaveVersion":"1.26","batteryLevel":74,"batteryLowNotification":true,"categories":["remotes"],"centralSceneSupport":[{"keyAttributes":["Pressed","Released","HeldDown"],"keyId":1},{"keyAttributes":["Pressed","Released","HeldDown"],"keyId":2},{"keyAttributes":["Pressed","Released","HeldDown"],"keyId":3},{"keyAttributes":["Pressed","Released","HeldDown"],"keyId":4},{"keyAttributes":["Pressed","Released","HeldDown"],"keyId":5},{"keyAttributes":["Pressed","Released","HeldDown"],"keyId":6},{"keyAttributes":["Pressed","Released","HeldDown"],"keyId":7},{"keyAttributes":["Pressed","Released","HeldDown"],"keyId":8}],"configured":true,"dead":false,"deadReason":"","defInterval":0,"deviceControlType":0,"deviceIcon":103,"emailNotificationID":0,"emailNotificationType":0,"endPointId":0,"firmwareUpdate":{"info":"","progress":0,"status":"UpToDate","updateVersion":"1.26"},"log":"","logTemp":"","manufacturer":"","markAsDead":true,"maxInterval":0,"minInterval":0,"model":"","nodeId":176,"parametersTemplate":"889","pendingActions":false,"productInfo":"1,155,3,0,163,5,1,26","pushNotificationID":0,"pushNotificationType":0,"remoteGatewayId":0,"saveLogs":true,"serialNumber":"h'0000000000000000000000000000000000ff","smsNotificationID":0,"smsNotificationType":0,"stepInterval":0,"updateVersion":"","useTemplate":true,"userDescription":""},"actions":{},"created":1632778740,"modified":1632778740,"sortOrder":479}`

**Comment by alexander-vitishchenko** [comment] 2021-10-18 14:32
@rwijbenga is there any chance you can send me the device, so I can implement and test its support by the QuickApp? (I'm at Europe/Ukraine)

It's fine if not, just need more time and possibly several iterations for testing/adjustments.

**Comment by rwijbenga** [comment] 2021-10-20 12:14
Hi Alexander,

I don't have a spare, all in use in my home.

I can make an extra donation, if you buy it there... ;)

**Comment by alexander-vitishchenko** [comment] 2021-10-30 20:06
Hi @rwijbenga,

I've just implemented Remote Controller device support, where it is represented as text sensor with the recently pressed button (with auto-expiring value in 10 seconds). 

+ as a bonus, each key is represented as a trigger visible at Home Assistant GUI ;)
+ I've implemented support for both Heatit Z-Push Button 8 and for Fibaro Keyfob

Feel free to check it out and let me know if you need anything else!

**Comment by alexander-vitishchenko** [comment] 2021-10-30 21:38
By the way - I've implemented passwordless mode to access Fibaro HC3. So you can remove these two redundant QA variables - "hc3Username" and "hc3Password"

Got inspired by another developer at Fibaro forum who apparently works on a similar integration

**Comment by rwijbenga** [comment] 2021-11-05 10:02
Will check this weekend! :)

**Comment by rwijbenga** [comment] 2021-11-05 17:12
Tried the new version... 

But I get this error:

[05.11.2021] [18:05:46] [ERROR] [QUICKAPP1112]: MQTT ERROR: {"code":2}
[05.11.2021] [18:05:46] [WARNING] [QUICKAPP1112]: MQTT username and/or password is possibly indicated wrongly

When I set development mode to true, it works without error. But nothing can be switched on or off,

So I think something is broken somewhere in the code. When I switch back to the previous version no problem at all... So it is not the MQTT server... 

Let me know when you need more info or testing.

**Comment by alexander-vitishchenko** [comment] 2021-11-05 18:40
I'm looking into it, meanwhile can you please advise how did you deploy the latest version of the QuickApp? By updating lua files from sources, or by uploading fqa file?

**Comment by alexander-vitishchenko** [comment] 2021-11-06 20:33
@rwijbenga I've just tested the latest version of the fqa file from GitHub - works for me, and thus I need more information to see why it doesn't work for you

Can you please advise whether you use username/password to access MQTT broker? And how did you deploy the latest version of the QuickApp to your Fibaro setup? Any extended logs would be appreciated (all logs since you start the QuickApp)

**Comment by rwijbenga** [comment] 2021-11-07 13:17
@alexander-vitishchenko I have tested it with installing the QuickApp, and teplacing the source files. Both the same result..

With or without username/password for the MQTT broker. Both tested with MQTT explorer. 

Here is the log, I removed the devices in between, as it would make a long list.... 

[07.11.2021] [14:12:36] [DEBUG] [QUICKAPP1322]: -------------------------
[07.11.2021] [14:12:36] [DEBUG] [QUICKAPP1322]: HC3 <-> MQTT BRIDGE
[07.11.2021] [14:12:36] [DEBUG] [QUICKAPP1322]: -------------------------
[07.11.2021] [14:12:37] [WARNING] [QUICKAPP1322]: Variable mqttClientId not found
[07.11.2021] [14:12:37] [WARNING] [QUICKAPP1322]: All is good - we have just autogenerated mqttClientId for you "HC3-1322-1636290757"
[07.11.2021] [14:12:37] [TRACE] [QUICKAPP1322]: MQTT Connection Parameters: {"password":"hc3","username":"hc3","keepAlivePeriod":15,"clientId":"HC3-1322-1636290757","lastWill":{"topic":"homeassistant\/hc3-dead","payload":"true"}}
[07.11.2021] [14:12:37] [DEBUG] [QUICKAPP1322]: MQTT connection established
[07.11.2021] [14:12:37] [DEBUG] [QUICKAPP1322]: Bridge mode: PRODUCTION
[07.11.2021] [14:12:37] [DEBUG] [QUICKAPP1322]: Device filter URI '/devices?visible=true&enabled=true'
[07.11.2021] [14:12:41] [DEBUG] [QUICKAPP1322]: Couldn't recognize device #2 - admin - com.fibaro.voipUser - HC_user
[07.11.2021] [14:12:41] [DEBUG] [QUICKAPP1322]: Couldn't recognize device #3 - YR Weather - com.fibaro.weather - com.fibaro.yrWeather
[07.11.2021] [14:12:41] [DEBUG] [QUICKAPP1322]: Device 7 spots #58 (Woonkamer) identified as light-dimmer
[07.11.2021] [14:12:41] [DEBUG] [QUICKAPP1322]: Device Pomp Keuken #61 (CV Ruimte) identified as switch-binary
[07.11.2021] [14:12:41] [DEBUG] [QUICKAPP1322]: Device Osmose Water #63 (Garage) identified as switch-binary
[07.11.2021] [14:12:41] [DEBUG] [QUICKAPP1322]: Couldn't recognize device #80 - Remco_12_Max - - iOS_device
[07.11.2021] [14:12:41] [DEBUG] [QUICKAPP1322]: Device 2 spots #85 (Woonkamer) identified as light-dimmer
[07.11.2021] [14:12:41] [DEBUG] [QUICKAPP1322]: Device Plafond #90 (Woonkamer) identified as light-dimmer
[07.11.2021] [14:12:41] [DEBUG] [QUICKAPP1322]: Device Schuine Muur Spots #97 (Woonkamer) identified as light-dimmer

-----------------------------------

[07.11.2021] [14:13:15] [DEBUG] [QUICKAPP1322]: Device Radiator #1294 (Cavia Kamer) identified as climate-default
[07.11.2021] [14:13:15] [DEBUG] [QUICKAPP1322]: Device Radiator Temp #1295 (Cavia Kamer) identified as sensor-temperature
[07.11.2021] [14:13:15] [DEBUG] [QUICKAPP1322]: Couldn't recognize device #1307 - Deur - com.fibaro.doorLock - com.fibaro.gerda
[07.11.2021] [14:13:15] [DEBUG] [QUICKAPP1322]: Couldn't recognize device #1309 - Voordeur - com.fibaro.doorLock - com.fibaro.gerda
[07.11.2021] [14:13:15] [DEBUG] [QUICKAPP1322]: Device Boiler #1311 (CV Ruimte) identified as light-binary
[07.11.2021] [14:13:15] [DEBUG] [QUICKAPP1322]: Device Temperatuur #1315 (Keuken) identified as sensor-temperature
[07.11.2021] [14:13:15] [DEBUG] [QUICKAPP1322]: Device Luchtvochtigheid #1316 (Keuken) identified as sensor-humidity
[07.11.2021] [14:13:15] [DEBUG] [QUICKAPP1322]: Device Thermostaat #1317 (Badkamer Remco) identified as climate-default
[07.11.2021] [14:13:15] [DEBUG] [QUICKAPP1322]: Device HC3 <-> MQTT Bridge #1322 (Woonkamer) identified as light-binary
[07.11.2021] [14:13:19] [DEBUG] [QUICKAPP1322]: ----------------------------------
[07.11.2021] [14:13:19] [DEBUG] [QUICKAPP1322]: Device discovery has been complete
[07.11.2021] [14:13:19] [DEBUG] [QUICKAPP1322]: ----------------------------------
[07.11.2021] [14:13:24] [DEBUG] [QUICKAPP1322]: ---------------------------------------------------
[07.11.2021] [14:13:24] [DEBUG] [QUICKAPP1322]: Started monitoring events from Fibaro Home Center 3
[07.11.2021] [14:13:24] [DEBUG] [QUICKAPP1322]: ---------------------------------------------------
[07.11.2021] [14:13:24] [ERROR] [QUICKAPP1322]: MQTT ERROR: {"code":2}
[07.11.2021] [14:13:24] [WARNING] [QUICKAPP1322]: MQTT username and/or password is possibly indicated wrongly
[07.11.2021] [14:13:24] [DEBUG] [QUICKAPP1322]: HC3-to-MQTT bridget shutdown sequence initiated
[07.11.2021] [14:13:24] [DEBUG] [QUICKAPP1322]: Disconnected from MQTT
[07.11.2021] [14:13:24] [DEBUG] [QUICKAPP1322]: HC3-to-MQTT bridge shutdown sequence complete
[07.11.2021] [14:13:28] [DEBUG] [QUICKAPP1322]: Disconnected from HC3 (got flagged to stop reading HC3 events)
[07.11.2021] [14:13:34] [DEBUG] [QUICKAPP1322]: Attempt to reconnect to MQTT...
[07.11.2021] [14:13:34] [WARNING] [QUICKAPP1322]: Variable mqttClientId not found
[07.11.2021] [14:13:34] [WARNING] [QUICKAPP1322]: All is good - we have just autogenerated mqttClientId for you "HC3-1322-1636290814"
[07.11.2021] [14:13:34] [TRACE] [QUICKAPP1322]: MQTT Connection Parameters: {"password":"hc3","username":"hc3","keepAlivePeriod":15,"clientId":"HC3-1322-1636290814","lastWill":{"topic":"homeassistant\/hc3-dead","payload":"true"}}
[07.11.2021] [14:13:34] [DEBUG] [QUICKAPP1322]: MQTT connection established
[07.11.2021] [14:13:34] [DEBUG] [QUICKAPP1322]: Bridge mode: PRODUCTION

**Comment by alexander-vitishchenko** [comment] 2021-11-08 00:53
@rwijbenga let me look at closer look at it tomorrow. I’ll try figure out possible conditions at you environment that lead to the issue. Then try to resolve it

**Comment by alexander-vitishchenko** [comment] 2021-11-08 20:48
@rwijbenga the other important question is whether you can provide logs from your MQTT broker side? This should be easy if MQTT broker is installed as part of Home Assistant setup.

I need to see more details than MQTT error code 2, because what it currently tells is that username/password/client id is wrong... but you mentioned all the connectivity parameters are good, so we need to find another reason for you to face the issue

**Comment by rwijbenga** [comment] 2021-11-09 10:18
@alexander-vitishchenko Found the problem, a keep alive timeout. As I have 255 devices..... It took to long. So I have set the time now to 30s. And no more connection problems. Your idea for the MQTT broker log's showed the error... :)

But I have a new problem, no device update's on the mqtt side. So I can turn on a light in Hass, but the slider does not update to the on position. And sensor also do not update, like door sensors... 

I am now using the older version again, as I needed the system to work. Let me know what log's / info you need for looking into the update problem with the new version. Maybe handy to chat on discord?

**Comment by alexander-vitishchenko** [comment] 2021-11-12 10:50
@rwijbenga good to know that the QuickApp is able to scale to hundreds of devices

1) I'll adjust the default keep-alive internal on weekend, so other people won't face MQTT connectivity issues in the future.

2) As for slider and door sensors, apologies, and would you be so kind to make some screenshots/video snippets demonstrating the issue? The ideal would be to share Fibaro QuickApp logs + Home Assistant MQTT integration logs. This can greatly help me find the root cause and I'll submit the fix as soon as possible.

3) Generally, feels like the QuickApp becomes bigger and bigger. It is pretty natural that new features may break something that worked perfectly in the past, even I do a bit of manual regression testing before publishing new QuickApp releases. 

I start to think about introducing automated smoke testing, which would catch defects before new features are pushed to users. But this requires both time and resource investments to set up a test automation environment... which would make sense to do if we had a bigger community of users... and it is a good question whether it makes sense to do now, perhaps worth keeping it "as is" and fix things after breaks are spotted by users, at least for now.

**Comment by rwijbenga** [comment] 2021-11-15 23:00
Hi Alexander,

If you have a light with dimmer in Home Assistant, and you turn it on or off, then the slider is also updated. That work with the old version. With the new version it is not updated. And does not move. Same with for example a door sensor. It does not update it state in Home Assistant in the new version anymore.

This is the log from a working setup:
[15.11.2021] [23:51:44] [DEBUG] [QUICKAPP1326]: Turn OFF for device #126
[15.11.2021] [23:51:45] [DEBUG] [QUICKAPP1326]: Turn OFF for device #126
[15.11.2021] [23:51:45] [DEBUG] [QUICKAPP1326]: CALL "setValue", with VALUE "53" for device #126
[15.11.2021] [23:51:52] [DEBUG] [QUICKAPP1326]: Turn OFF for device #126
[15.11.2021] [23:51:54] [DEBUG] [QUICKAPP1326]: CALL "setValue", with VALUE "99" for device #126

This from the not working setup:
[15.11.2021] [23:47:11] [DEBUG] [QUICKAPP1372]: Turn ON for device #126
[15.11.2021] [23:47:11] [DEBUG] [QUICKAPP1372]: CALL "setValue", with VALUE "40" for device #126
[15.11.2021] [23:47:11] [DEBUG] [QUICKAPP1372]: Turn OFF for device #126
[15.11.2021] [23:47:43] [DEBUG] [QUICKAPP1372]: Turn ON for device #126
[15.11.2021] [23:47:47] [DEBUG] [QUICKAPP1372]: Turn ON for device #126
[15.11.2021] [23:49:47] [DEBUG] [QUICKAPP1372]: Turn OFF for device #126

Looks like the CALL "setValue", with VALUE "40" for device #126 is not working in the new version....

Are you also on Discord? Maybe handy for uploading more information...

**Comment by alexander-vitishchenko** [comment] 2021-11-16 00:15
@rwijbenga thanks for the logs! Let me explore it in details. Hopefully it helps me find and fix the issue.

If not - let’s go with Discord, sounds like a great approach to see your environment, and issue root cause to get it resolved.

**Comment by alexander-vitishchenko** [comment] 2021-11-20 21:48
@rwijbenga hi

1) I've fixed binary sensor status updates (including but not limited to door sensors). This regression defect is caused by a bit of refactoring that I did in order to simplify the codebase and improve the maintainability in the long run.

2) I've also increased the default MQTT keep-alive period from 15 to 60 seconds. 

3) I suspect the issue with Dimmer updates could be still there, but the other two issues are supposed to be fixed now.

Can you please have a look at the newer version and tell me if it works for you?

**Comment by alexander-vitishchenko** [comment] 2021-12-01 06:54
@rwijbenga have you had a chance to check the new version of the QuickApp?

**Comment by rwijbenga** [comment] 2021-12-01 09:51
@alexander-vitishchenko 

Ooops sorry!!!

 I did test it and thought I have posted a reply last week, think I did not click on comment before closing my notebook... :(

But it still lag's and does not correctly update the status as the old quickapp. I also noticed the CPU load on the HC3 is with the new app very high. every second almost 100%. And with the old app no spikes at all... 

So something in the code change does not work correctly, and slows it down. Switching to the old app solves everything. So it is not the mqtt broker or home assistant.

Maybe handy to test some more on discord, same username as here. :)

**Comment by alexander-vitishchenko** [comment] 2021-12-01 20:09
@rwijbenga agree, sounds like Discord would be the most effective way to investigate the issue

My username is vid_ua#1643

Let's have a call around Saturday afternoon/evening time, or Sunday monday/noon?

**Comment by alexander-vitishchenko** [comment] 2021-12-27 22:12
This comment is just to track the history of the changes:
 - we had a call with @rwijbenga today => found the performance issue's root cause => fixed it
 - I've additionally disabled debug messages for "PluginChangedViewEvent", as it's not intended for translation to Home Assistant world => no need to alarm QuickApp users

**Closed by alexander-vitishchenko** 2021-12-27 22:12 UTC
Labels: New device

**Comment by alexander-vitishchenko** [comment] 2022-01-08 20:33
@rwijbenga by the way, have you had a chance to donate for "Heatit Z-Push Button 8” purchase? :)
